id: ${random.uuid}
secret: ${random.value}
age: ${random.int(1,150)}
randomLong: ${random.long}
app:
  name: MyApp
  # 使用占位符
  description: ${app.name} 是一个项目

my:
  # 指定列表
  servers:
  - dev.example.com
  - another.example.com
  info:
    first-name: smith
    name: make
    age: 18
    address: beijing
    session-timeout: 10
    # 指定单位
    read-timeout: 30s
    buffer-size: 8

    code:
      # 包含特殊字符时的处理
      "[a*]": 1
      b: 2
      c: 3


spring:
  profiles:
    # 激活配置
    active: dev # pro,cen
server:
  address: 192.168.1.101

# 定义多个配置
---
spring:
  profiles: dev
server:
  address: 127.0.0.1
---
spring:
  profiles: pro & cen
server:
  address: www.baidu.com